### ISSUE TITLE
add CLI to allow easier automation

### ISSUE THREAD

**Issue by eniad** [nasa/sitepod#2]
Here's the pertinent part of the ESDSWG Search Relevancy email thread between @eniad and @lewismc:

> 2. Can the sitemap generation be automated with sitepod? We'd prefer a command line interface for cronjobs, but need some way to programmatically run the generator. We would do this either periodically or when new content (like a new data set) is added.
> 
> This is not yet implemented and I would need to work on it a wee bit. I think it should be a priority so I will try to write some documentation and begin work on this shortly. I agree with you here, this needs to be automated and without a CLI is a near impossible.

**Comment by lewismc** [comment]
http://www.php-cli.com/

**Comment by lewismc** [comment]
@eniad I wonder if you got around to trying the project out recently? I've been making quite a lot of improvements recently and the documentation is very easy to follow. Let me know how you get on.

**Comment by eniad** [comment]
@lewismc, TL:DR: I have Sitepod install and working on one of our sites and I'm working on the other, more complicated sites.

I have Sirepod installed and working on the ORNL DAAC MODIS subsetting site: https://modis.ornl.gov. The MODIS subsetting site is a smaller site so it's easier to maintain the sitemap and quicker to crawl the site.

So far things have gone smoothly. The settings and function is straight forward. I haven't actually played with automating the sitemap generation yet.

I am working on our other sites. The most complicated site is our main website: https://daac.ornl.gov
It has a mixture of html and Perl cgi pages.

Sorry, I haven't responded sooner. Sitepod is my Friday afternoon fun project. We've also got our UWG this week, so that's taken most of my time.

**Comment by lewismc** [comment]
Thanks for the update @eniad I get it :) Let's keep things moving here and hopefully we can improve Sitepod as well as crawling of DAAC sites.

**Comment by lewismc** [comment]
Fixed via #37
