### ISSUE TITLE
Call to undefined function split()

### ISSUE THREAD

**Issue by Pyradur** [nasa/sitepod#36]
I'm using php 7.2x
After starting sitepod I got the following error-message:
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined function split() in /var/www/vhosts/domainname.tld/httpdocs/vendor/nasa/sitepod/inc/classes/Crawler.class.php:340

This is because split() is in php 7.x removed!
Therefore split() must be replaced with str_split().
Because I'm not firm with GIT I can't do that.

**Comment by sigee** [comment]
Hi @Pyradur,
I've checked what you wrote and I found that you use an old sitepod version.
I've already fixed the split issue. We just haven't release it yet.
You can download the newest version from [here](https://github.com/nasa/sitepod/archive/master.zip).

**Comment by lewismc** [comment]
@Pyradur I made a 1.6.0 release of the codebase so it should now be available. Thank you for registering the issue.

**Comment by Pyradur** [comment]
Hi there,

after "installing" (copying) the newst version and starting sitepod I hat the following error_messages in my log-file:

AH01071: Got error 'PHP message: PHP Warning: include_once(/var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/sitepod/inc/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/sitepod/inc/startup.php on line 31
PHP message: PHP Warning: include_once(): Failed opening '/var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/sitepod/inc/../vendor/autoload.php' for inclusion (include_path='.:/opt/plesk/php/7.1/share/pear:./inc:./inc/functions:./inc/classes:./settings:./templates') in /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/sitepod/inc/startup.php on line 31
PHP message: PHP Fatal error: Uncaught Error: Class 'Sitepod\\GeoIp' not found in /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/sitepod/inc/startup.php:34
Stack trace:
#0 /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/sitepod/index.php(17): require_once()
#1 {main}
 thrown in /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/sitepod/inc/startup.php on line 34'


Mit freundlichen Grüßen

Reinhold Riedersberger

DVI-Service
Reinhold Riedersberger
Oderstraße 98
78052 Villingen-Schwenningen

Telefon : (07721) 70057
Telefax : (07721) 70058
eMail   : info@dvi-service.de
Internet: www.dvi-service.de
--------------------------------------------------------------------

Hi @Pyradur,
I've checked what you wrote and I found that you use an old sitepod version.
I've already fixed the split issue. We just haven't release it yet.
You can download the newest version from here.

**Comment by sigee** [comment]
Hi @Pyradur,

Sitepod is depending on **composer**.
Here is the installation giude:
https://github.com/nasa/sitepod/wiki/Sitepod-Installation

BTW: I guess you need to run ```composer install```, but you should check the guide.

**Comment by Pyradur** [comment]
Hi there,

after using composer I got the following error:

Maybe you can help me...?

AH01071: Got error 'PHP message: PHP Warning: include_once(/var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/vendor/nasa/sitepod/inc/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/vendor/nasa/sitepod/inc/startup.php on line 31\nPHP message: PHP Warning: include_once(): Failed opening '/var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/vendor/nasa/sitepod/inc/../vendor/autoload.php' for inclusion (include_path='.:/opt/plesk/php/7.1/share/pear:./inc:./inc/functions:./inc/classes:./settings:./templates') in /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/vendor/nasa/sitepod/inc/startup.php on line 31\nPHP message: PHP Fatal error: Uncaught Error: Class 'Sitepod\\GeoIp' not found in /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/vendor/nasa/sitepod/inc/startup.php:34\nStack trace:\n#0 /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/vendor/nasa/sitepod/index.php(17): require_once()\n#1 {main}\n thrown in /var/www/vhosts/dvi-service.de/httpdocs/etikettenagentur.de/admin_fremd/vendor/nasa/sitepod/inc/startup.php on line 34\n' 




Hi @Pyradur,
Sitepod is depending on composer.
Here is the installation giude:
https://github.com/nasa/sitepod/wiki/Sitepod-Installation
BTW: I guess you need to run composer install, but you should check the guide.

**Comment by lewismc** [comment]
Hi @Pyradur If I were you I would purge all Sitepod material and run from a clean installation.
