### ISSUE TITLE
Fix timezone warning upon submit success

### ISSUE THREAD

**Issue by lewismc** [nasa/sitepod#4]
Upon successful submission and completion of Sitemap generation, I see the following list of error presented to me

<img width="1409" alt="screen shot 2017-03-16 at 1 32 52 pm" src="https://cloud.githubusercontent.com/assets/1165719/24017478/76fb165a-0a4d-11e7-9ab8-452ebd974439.png">

We should address the warnings.

**Comment by lewismc** [comment]
@eniad do you have any idea how to fix this issue? I had a crack at it but I am not able to select the local timezone based upon the machine timezone settings.

**Comment by sigee** [comment]
Hi @lewismc,
Sorry for the say in, but I would mention that, there are two solution to avoid this warning.
1. In the php.ini you can set the default timezone. [link](http://php.net/manual/en/datetime.configuration.php#ini.date.timezone)
2. In the php code you can set the actual timezone. [link](http://php.net/manual/en/function.date-default-timezone-set.php)

I think you can set both of them if it is needed. The ini means the default fallback, but it is good when you can see the actual value in the code.

**Comment by lewismc** [comment]
Hi @sigee I appreciate you chiming in. Did you see the pull request I submitted? If you could scope it out and provide input it would be appreciated. Thank you

**Comment by lewismc** [comment]
Here is the PR https://github.com/nasa/sitepod/pull/10/files, I think it needs to be changed to be adaptive rather than restricted to UTC.

**Comment by sigee** [comment]
@lewismc,
Unfortunatelly there is no way in standard php to get the user's timezone.
You can get the user's IP address and use a geoip api to get the location and timezone data.
Eg.: http://smart-ip.net/geoip-api
```php
$ip     = $_SERVER['REMOTE_ADDR']; // means we got user's IP address 
$json   = file_get_contents( 'http://smart-ip.net/geoip-json/' . $ip);
// maybe it's good to add some checks (if/else you've got an answer and if json could be decoded, etc.)
$ipData = json_decode( $json, true);

if ($ipData['timezone']) {
    $timeZone = new DateTimeZone( $ipData['timezone']);
    date_default_timezone_set($timeZone->getName())
}
else {
    //not needed when php.ini is set.
    date_default_timezone_set('UTC');
}
```
The UTC should be set in the php.ini as I mentioned before.
